import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css';
import SideMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";
import { ToastContainer, toast } from 'react-toastify';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1d2d3a]">

        <div className="grid grid-cols-5">

       
            <SideMenu />
          
          <ToastContainer
          autoClose={1200}
          />
          <div className="col-span-4">
            <Header />
            {children}

          </div>
        </div>


      </body>
    </html>
  );
}
